[package]
name = "raytracer"
version = "0.1.0"
authors = ["Pascal Spörri <pascal.spoerri@env.ethz.ch>"]

[dependencies]
nalgebra = "0.8.2"
num-traits = "0.1.32"
image = "0.9.0"
rand = "0.3"
#scoped_threadpool = "0.1.7"
threadpool = "1.3.0"